export enum CategoryTicket {
  SOFTWARE = 'SOFTWARE',
  HARDWARE = 'HARDWARE',
  NETWORK = 'NETWORK',
  OPERATING_SYSTEM = 'OPERATING_SYSTEM',
  PRINTERS = 'PRINTERS',
  SECURITY = 'SECURITY',
  OTHER = 'OTHER',
}
